# Generated by Django 5.1.7 on 2025-04-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'description', 'category')},
        ),
    ]
